// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioPlayerController from "./audio_player_controller"
application.register("audio-player", AudioPlayerController)

import DarkModeToggleController from "./dark_mode_toggle_controller"
application.register("dark-mode-toggle", DarkModeToggleController)